//! `ply.lock` — machine truth. Exact versions + sha256 per package.
//! Deploys use the lockfile only; resolution happens at build/update time.

use std::path::Path;

use semver::Version;
use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Lockfile {
    /// Flattened closure in overlay order: app deps first, base last
    /// (lowerdir order, deps below dependents).
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct LockedPackage {
    pub name: String,
    pub version: Version,
    pub source: String,
    pub sha256: String,
}

impl Lockfile {
    pub fn parse(text: &str) -> Result<Self> {
        toml::from_str(text).map_err(|e| Error::Manifest(format!("ply.lock: {e}")))
    }

    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path).map_err(|source| Error::Io {
            path: path.to_path_buf(),
            source,
        })?;
        Self::parse(&text)
    }

    pub fn to_toml(&self) -> String {
        let header = "# ply.lock — generated by `ply build`; do not edit by hand.\n";
        let body = toml::to_string_pretty(self).expect("lockfile serializes");
        format!("{header}{body}")
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        std::fs::write(path, self.to_toml()).map_err(|source| Error::Io {
            path: path.to_path_buf(),
            source,
        })
    }
}
