[package]
name = "hello-bun"
version = "0.1.0"
base = "debian@13"
entrypoint = ["bun", "run", "index.ts"]
include = ["index.ts", "index.html"]

[dependencies]
bun = "1.4"

[ports]
web = 3000

[sources]
default = "https://registry.plybox.sh/ply/{package}"
